# Generated by Django 3.2.4 on 2022-08-23 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_APP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CCBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_name', models.CharField(max_length=200)),
                ('add', models.CharField(max_length=400)),
                ('mobile', models.BigIntegerField()),
                ('card_no', models.BigIntegerField()),
                ('card_limit', models.BigIntegerField()),
                ('card_expiry', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
    ]
